POST http://localhost:8888/moves
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hcnTDrW4iLCJlbWFpbCI6Im1hcnRpbkB0ZXN0LmNvbSIsImlhdCI6MTY0MzUxNzg4NiwiZXhwIjoxNjQzNTIxNDg2fQ.OQrLnuGhCykXTbBfCGyo-GRQwU7rqGyugh36xADfyS8

{
    "description": "Move 22",
    "amount": "99.99",
    "type": "income",
    "date": "2017-01-01"
}